spring.application.name=reservation-api

spring.datasource.url=${CAMPUSRESERVE_DATABASE_URL:jdbc:postgresql://localhost:5434/campusreserve}
spring.datasource.username=${CAMPUSRESERVE_DATABASE_USERNAME:campusreserve}
spring.datasource.password=${CAMPUSRESERVE_DATABASE_PASSWORD:campusreserve}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true