spring.application.name=reservation-api

spring.datasource.url=${CAMPUSRESERVE_DATABASE_URL:jdbc:postgresql://localhost:5434/campusreserve}
spring.datasource.username=${CAMPUSRESERVE_DATABASE_USERNAME:campusreserve}
spring.datasource.password=${CAMPUSRESERVE_DATABASE_PASSWORD:campusreserve}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.data.redis.host=${CAMPUSRESERVE_REDIS_HOST:localhost}
spring.data.redis.port=${CAMPUSRESERVE_REDIS_PORT:6380}
spring.data.redis.connect-timeout=500ms
spring.data.redis.timeout=500ms
spring.data.redis.repositories.enabled=false
