spring.application.name=reservation-api

spring.datasource.url=${CAMPUSRESERVE_DATABASE_URL:jdbc:postgresql://localhost:5434/campusreserve}
spring.datasource.username=${CAMPUSRESERVE_DATABASE_USERNAME:campusreserve}
spring.datasource.password=${CAMPUSRESERVE_DATABASE_PASSWORD:campusreserve}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.data.redis.host=${CAMPUSRESERVE_REDIS_HOST:localhost}
spring.data.redis.port=${CAMPUSRESERVE_REDIS_PORT:6380}
spring.data.redis.connect-timeout=500ms
spring.data.redis.timeout=500ms
spring.data.redis.repositories.enabled=false

campusreserve.kafka.host=${CAMPUSRESERVE_KAFKA_HOST:localhost}
campusreserve.kafka.port=${CAMPUSRESERVE_KAFKA_PORT:9094}
spring.kafka.bootstrap-servers=${campusreserve.kafka.host}:${campusreserve.kafka.port}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.consumer.group-id=campusreserve-reservation-audit-v1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.erfansadri.campusreserve.reservation.messaging
spring.kafka.consumer.properties.spring.json.value.default.type=com.erfansadri.campusreserve.reservation.messaging.ReservationLifecycleEvent

campusreserve.outbox.publisher.enabled=${CAMPUSRESERVE_OUTBOX_PUBLISHER_ENABLED:true}
campusreserve.outbox.publisher.fixed-delay-ms=${CAMPUSRESERVE_OUTBOX_PUBLISHER_FIXED_DELAY_MS:5000}
